### ISSUE TITLE
Link Phenotypes <-> SNPs

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/snpr#242]
So far the phenotypes and the SNPs are rather independent from each other, making it hard to link one to the other. But in principle we already have the information needed to link them, at least in a really low level way: The papers attached to the SNPs might have the phenotype names in the title. 

Using those we could link certain SNPs to phenotypes and vice versa link phenotypes to SNPs. I think that could make it more useful for people who are more into using openSNP for browsing their own genomes. What do you think?

**Comment by philippbayer** [comment]
Hmm we could have a worker that parses the SNP's paper abstracts/names, extracts all words that appear in the phenotype descriptions or names, and then creates a SnpPhenotypeLink (or sth. like that), to be displayed in another tab on the SNP's show-page

We could even then link the recommendify results - since the phenotypes are linked by similarity in recommendify we can start from the SnpPhenotypeLink and add other phenotypes

**Comment by gedankenstuecke** [comment]
Yes, I think that sounds like a good idea. I don't think that those recommendations for phenotypes etc. would be medical information. It's not that we're generating any reports. So what about the below?

### Tasks
- [ ] Creating SnpPhenotypeLink through paper titles 
- [ ] Add those Links to SNP pages
- [ ] Additionally display similar phenotypes

**Comment by vivekiitkgp** [comment]
@gedankenstuecke You can assign this issue to me. ;)

**Comment by gedankenstuecke** [comment]
Happy to do so! 👍

**Comment by vivekiitkgp** [comment]
- Changes related to database schema, models and a demo is available in https://github.com/vivekiitkgp/snpr/tree/phenotype_snp
